#!/bin/bash
#SBATCH --account=bioinfo_serv
#SBATCH --partition=bioinfo
#SBATCH --job-name=cutadapt   #job name
#SBATCH --mail-type=END # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=gonzalo.n.moreno@gmail.com # Where to send mail        
#SBATCH --mem-per-cpu=5gb # Per processor memory
#SBATCH --cpus-per-task=2
#SBATCH -t 15:00:00     # Walltime
#SBATCH -o %j_fastqc.out # Name output file 
#SBATCH --error=%j_fastqc.err
##SBATCH --file=
##SBATCH --initaldir=

# cutadapt steps for trimming of reads generated by NEXTflex library
# modules
module load miniconda/3.6

# arguments

fastq=$1
sample=$(basename "$fastq" .fastq.gz)
output=$2

# command line

# NEXTFLEX
cutadapt -a TGGAATTCTCGGGTGCCAAGG -o ${output}/${sample}.trim1.fastq.gz --minimum-length 23 $fastq # TruSeq Small RNA
cutadapt -u 4 -u -4 -o ${output}/${sample}.trim2.fastq.gz ${output}/${sample}.trim1.fastq.gz
cutadapt --minimum-length 17 --maximum-length 25 -o $output/${sample}_l17_25.fq ${output}/${sample}.trim2.fastq.gz

# TruSeq™ single index (previously LT)
# cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -o ${output}/${sample}.trim1.fastq.gz $fastq # TruSeq Adapter 
# cutadapt --minimum-length 17 --maximum-length 25 -o $output/${sample}_l17_25.fq ${output}/${sample}.trim1.fastq.gz
